#!/bin/sh
feeds=`grep -Po '(?<=href=")[^"]*' < /dev/stdin |uniq -u |grep -vf ~/.newsboat/github-issue-exclude |awk -F / '{ if($4 == "issues") { printf "%s", "&f=http%3A%2F%2Flocalhost%3A10992%2Findex.php%3Faction%3Ddisplay%26bridge%3DGithubIssue%26context%3DIssue+comments%26i%3D"$5"%26u%3D"$2"%26p%3D"$3"%26format%3DAtom"} }'`
curl -s "http://localhost:8000/atom?n=0$feeds"
